### ISSUE TITLE
Support for jitsi secure JWT

### ISSUE THREAD

**Issue by d3xt3r01** [eliocamp/thelounge-plugin-jitsi#2]
Assumming the link is generated server-side a shared secret can be set to generate a JWT to use with a private jitsi instance.
Could look like this to preserve compatibility with other services

Header:
```
{ "typ": "JWT", "alg": "HS256" }
```

Payload:
```
{ "account": "", "channel": <roomname>, "exp": time()+60, "iss": <theircdservername>, "joined": true, "modes": [], "net_modes": [], "nick": <nick>, "time_joined": time()
```
"modes" can have the current mode for the user that could enable the moderator privileges in jitsi.
"roomname" can be a `#channel` or `query+user1+user2` in clear text.

Both the header and payload have to have the padding =='s stripped and a little bit recoded

Php example:
```
function base64url_encode($str) {
        return rtrim(strtr(base64_encode($str), '+/', '-_'), '=');
}
$h = str_replace("=", "", base64url_encode(json_encode($h)))
```

The final jwt token result can be generated like this:
```
        $tosign = $encodedheader.".".$encodedpayload;

        $sig = hash_hmac('sha256', $tosign, $secret, true);
        $sig = base64url_encode($sig);
        $sig = str_replace("=", "", $sig);

        $jwt =  $encodedheader.".".$encodedpayload.".".$sig;
```

The link should look like:
```
<jitsiurl>/<encodedroomname>?jwt=<token>
```

This is what I use for the <encodedroomname>
```
function encodedroomname($chanstring){
        $s = '<servername>/'.$chanstring;
        $ret = '';
        foreach(str_split($s) as $a){
                $ret .= dechex(ord($a));
        }
        return $ret;
}
```

**Comment by eliocamp** [comment]
Hi. This plugin uses the free service at meet.jit.si, which I don't think supports private rooms. Also, the link is generated client-side, not on the server. It basically creates a random url an sends it via query to the nicks specified in the command. 

I made this as a quick and dirty way of allowing users to create video meetings, but I don't have time or knowledge (my grasp of javascript is spotty at best) to change things. Please, feel free to fork this repo to include your proposed changes, though!
